version: "3"

networks:
  influx:
    name: influx-frontend

services:
  influxdb:
    container_name: dk-telegraf
    image: telegraf:latest
    restart: always
    ports:
      - "8086:8086"
      - "8125:8125"      
      - "8125:8125"
      - "8092:8092"
      - "8094:8094"      
    environment:
      TZ: ${TIME_ZONE}
    env_file:
      - ../.env
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
      - ./influxdb/config.yml:/etc/influxdb2/config.yml
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - influx

  dk-grafana:
    container_name: dk-grafana
    image: grafana/grafana:8.5.15-ubuntu
    restart: always
    ports:
      - "3000:3000"
    environment:
      TZ: ${TIME_ZONE}
    depends_on:
      - influxdb
    env_file:
      - ../.env
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/dashboards
    networks:
      - influx


