version: "3"


services:
  influxdb:
    container_name: dk-telegraf
    image: telegraf:alpine
    restart: always
    ports:
      - "8086:8086"
      - "8125:8125"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    env_file:
      - .env
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - ./influxdb/config.yml:/etc/influxdb2/config.yml
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  dk-grafana:
    container_name: dk-grafana
    image: grafana/grafana:8.5.15-ubuntu
    restart: always
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    environment:
      TZ: ${TIME_ZONE}
    depends_on:
      influxdb
    env_file:
      - .env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/dashboards



