version: "3"

services:
  pihole:
    container_name: ${CONTAINER_PIHOLE_NAME}
    image: pihole/pihole:latest
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "${PIHOLE_HTTP_PORT}:80/tcp"
      - "8443:443/tcp"
    environment:
      TZ: ${TIME_ZONE}
      WEBPASSWORD: '${PIHOLE_WEB_PASSWORD}'
      PIHOLE_DNS_: '1.1.1.1;8.8.8.8'
      REV_SERVER_DOMAIN: 'valhalla'
      REV_SERVER_TARGET: '172.16.99.254'
      REV_SERVER: '172.16.99.254'
      DHCP_ACTIVE: 'false'
      DNSSEC: 'true'
    volumes:
      - '${PIHOLE_DIR_ETC}:/etc/pihole'
      - '${PIHOLE_DIR_DNS}:/etc/dnsmasq.d'
      - '${PIHOLE_DIR_LOG}:/var/log/pihole'
  
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=cleberson
      - INFLUXDB_ADMIN_PASSWORD=password
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=cleberson
      - GF_SECURITY_ADMIN_PASSWORD=password

  dk-speed:
    image: dk-speed
    container_name: dk-speed
    restart: always
    volumes:
      - ./speedtest:/speedtest

volumes:
  influxdb-storage:
  grafana-storage:
