version: "3"

services:
  pihole:
    container_name: ${CONTAINER_PIHOLE_NAME}
    image: pihole/pihole:latest
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "${PIHOLE_HTTP_PORT}:80/tcp"
      - "8443:443/tcp"
    environment:
      TZ: ${TIME_ZONE}
      WEBPASSWORD: '${PIHOLE_WEB_PASSWORD}'
      PIHOLE_DNS_: '1.1.1.1;8.8.8.8'
      REV_SERVER_DOMAIN: ${YOUR_LOCAL_DOMAIN}
      REV_SERVER_TARGET: ${YOUR_ROUTER_IP}
      REV_SERVER: ${YOUR_ROUTER_IP}
      DHCP_ACTIVE: 'false'
      DNSSEC: 'true'
      REV_SERVER_CIDR: ${YOUR_LOCAL_NETWORK}
      DHCP_ROUTER: ${YOUR_ROUTER_IP}
      PIHOLE_DOMAIN: ${YOUR_LOCAL_DOMAIN}
    volumes:
      - '${PIHOLE_DIR_ETC}:/etc/pihole'
      - '${PIHOLE_DIR_DNS}:/etc/dnsmasq.d'
      - '${PIHOLE_DIR_LOG}:/var/log/pihole'

  dk-tor:
    container_name: dk-tor
    image: dk-tor:latest
    ports:
      - "${TOR_PORT}:9150"
    restart: unless-stopped

